---
title: "Project 1 - Frito Lay Attrition Analysis"
author: "Kyle Davisson"
date: "2025-03-10"
output: html_document
---
Youtube link: https://youtu.be/yDTy-NDOuaE

```{r}
##Load Libraries
library(GGally)
library(dplyr)
library(e1071)
library(tidyverse)
library(ggthemes)
library(plotly)
library(caret)
library(class)
library(reshape2)
library(scales)
```

```{r}
##Load and Clean Data
fl = read.csv(file.choose())
fl_clean = fl %>% select(-c(EmployeeCount, EmployeeNumber,Over18,StandardHours))
fl_clean = fl_clean %>% mutate(across(where(is.character), as.factor))

fl_fac = fl_clean %>% mutate(across(c(8,10,13,14,16,20,23,24,25,27,28), as.factor))
fl_num = fl_clean %>% mutate(Attrition = as.numeric(Attrition) - 1) %>% select(where(is.numeric))

str(fl_fac)
str(fl_clean)
```

```{r}
##Load and Clean Data
fl = read.csv(file.choose())
fl_clean = fl %>% select(-c(EmployeeCount, EmployeeNumber,Over18,StandardHours))
fl_clean = fl_clean %>% mutate(across(where(is.character), as.factor))

fl_fac = fl_clean %>% mutate(across(c(8,10,13,14,16,20,23,24,25,27,28), as.factor))
fl_num = fl_clean %>% mutate(Attrition = as.numeric(Attrition) - 1) %>% select(where(is.numeric))

str(fl_fac)
str(fl_clean)
```

```{r}
####Opening Plot
Fig1 = fl_clean %>% ggplot(aes(x = "", fill = Attrition)) + geom_bar(width = 1) + coord_polar("y", start = 0) +
  theme_void() + labs(title = "Overall Attrition") +
  geom_text(stat = "count", aes(label = paste0(..count.., "\n", percent(..count../sum(..count..)))), position = position_stack(vjust = 0.5), size = 6, color = "white") +
  theme(plot.title = element_text(hjust = 0.5,  vjust = -2.5), legend.position = c(0.5, 0.05), legend.direction = "horizontal", legend.title = element_blank()) +
  scale_fill_discrete(labels = c("Percent Retention", "Percent Attrition"))
```

```{r}
#Job Involvement
Fig2.1 = fl_fac %>%
  group_by(JobInvolvement) %>%
  summarize(total_count = n(), attrition_count = sum(Attrition == "Yes"), meanage = mean(Age)) %>%
  mutate(perc_attrition = (attrition_count / total_count) * 100) %>%
  ggplot(aes(x = JobInvolvement, y = perc_attrition, fill = JobInvolvement)) +
  geom_bar(stat = "identity") + ylim(0,50) +
  labs(title = "Attrition Percentage by Job Involvement", x = "Job Involvement Rating", y = "Percent") + 
  theme(legend.position = "none",axis.text = element_text(size = 10), plot.title = element_text(hjust = .5)) +
  geom_text(aes(label = paste0(round(perc_attrition, 1), "%")), vjust = 1.5, color = "white", size = 5)
```

```{r}
#Age
Fig3 = fl_fac %>% ggplot(aes(x = Attrition,y = Age,fill = Attrition)) + geom_boxplot() + stat_summary(aes(label = ..y..,),fun = median, geom = "text",position = position_nudge(x = -0.48),size = 4) + labs(x = NULL, y = "Age") + theme(legend.position = "none")

```

```{r}
#MeanAge vs JobRole
Fig4 = fl_fac %>% group_by(JobRole) %>% summarize(total_count = n(), attrition_count = sum(Attrition == "Yes"), MeanAge = mean(Age)) %>%
  mutate(perc_attrition = (attrition_count / total_count) * 100) %>%
  ggplot(aes(x = MeanAge, y = perc_attrition, color = JobRole)) + geom_point() + xlim(30,50)+ylim(0,50) +
  labs(title = "Attrition Percentage by Mean Age and Job Role", x = "Mean Age", y = "Percentage of Attrition")
```

```{r}
#
Fig5 = fl_fac %>% group_by(JobRole) %>% summarize(total_count = n(), attrition_count = sum(Attrition == "Yes"), MeanAge = mean(Age)) %>%
  mutate(perc_attrition = (attrition_count / total_count) * 100) %>%
  ggplot(aes(x = MeanAge, y = perc_attrition)) + geom_point(aes(color = JobRole))+ geom_smooth(method = "lm", se = FALSE) + xlim(30,50)+ylim(0,50) +
  labs(title = "Attrition Percentage by Mean Age and Job Role", x = "Mean Age", y = "Percentage of Attrition")
```

```{r}
##Looking at Distance from Home
DistAttr = fl_fac %>% ggplot(aes(DistanceFromHome, fill = Attrition)) + geom_density() + facet_grid(~Attrition)
```

```{r}
##Department vs. Job Level
Fig7 = fl_fac %>% group_by(Department,JobLevel) %>% 
  summarize(total_count = n(), attrition_count = sum(Attrition == "Yes"), MeanAge = mean(Age)) %>%
  mutate(perc_attrition = (attrition_count / total_count) * 100) %>%
  ggplot(aes(x = JobLevel, y = perc_attrition, fill = JobLevel)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  geom_text(aes(label = paste0(round(perc_attrition, 1), "%")), position = position_dodge(width = 0.9), vjust = 1.5, color = "white", size = 3) +
  labs(title = "Attrition by Job Level Across Departments", x = "Job Level", y = "Percent Attrition") + 
  theme(legend.position = "none", strip.text = element_text(size = 10), axis.text.x = element_text(size = 10)) + facet_grid(~Department)
```

```{r}
  ##MaritalStatus
Fig8 = fl_fac %>% 
  group_by(MaritalStatus) %>% 
  summarize(total_count = n(), attrition_count = sum(Attrition == "Yes"),MeanAge = mean(Age)) %>%
  mutate(perc_attrition = (attrition_count / total_count) * 100) %>%
  ggplot(aes(x = MaritalStatus, y = perc_attrition, fill = MaritalStatus)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  geom_text(aes(label = paste0(round(perc_attrition, 1), "%")), 
            position = position_dodge(width = 0.9), 
            vjust = 1.5, color = "white", size = 5) + 
  labs(title = "Attrition by Marital Status", x = "", y = "Percent Attrition") + 
  theme(legend.position = "none", axis.text.x = element_text(size = 12))
```

```{r}
  ##Income
Fig9 = fl_fac %>% ggplot(aes(x = Attrition, y = MonthlyIncome, fill = Attrition)) + geom_boxplot() + 
  stat_summary(aes(label = ..y..,),fun = median, geom = "text",vjust = -0.5,size = 4) +
  labs(title = "Monthly Income Distribution by Attrition", x = "Attrition", y = "Monthly Income") + 
  theme(legend.position = "none", axis.text = element_text(size = 10))
Fig10 = as.data.frame(fl_fac %>% group_by(JobRole)%>% summarize(meanIncome = mean(MonthlyIncome), medianIncome = median(MonthlyIncome),count = n(), percattr = sum(Attrition == "Yes") / n() * 100)) %>%
 ggplot(aes(x = meanIncome, y = percattr, color = JobRole)) + geom_point() + xlim(0,20000) + ylim(0,50) +
  labs(title = "Mean Monthly Income and Job Role", x = "Mean Monthly Income", y = "Attrition Percentage", color = "Job Role")
```

```{r}
  ##Overtime                                                                                                                
Fig11 = fl_fac %>% 
  group_by(OverTime) %>% 
  summarize(total_count = n(), attrition_count = sum(Attrition == "Yes")) %>%
  mutate(perc_attrition = (attrition_count / total_count) * 100) %>%
  ggplot(aes(x = OverTime, y = perc_attrition, fill = OverTime)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  geom_text(aes(label = paste0(round(perc_attrition, 1), "%")), vjust = 1.5, color = "white", size = 5) + 
  labs(title = "Attrition Distribution by Overtime Status", x = "Overtime Status", y = "Percent") + 
  scale_x_discrete(labels = c("No" = "No Overtime", "Yes" = "Overtime")) + ylim(0, 40) +
  theme(legend.position = "none", axis.text.x = element_text(size = 14))
```

```{r}
  ##StockOptionLevel
Fig12 = fl_fac %>% group_by(StockOptionLevel)%>% 
  summarize(Count = n(), perc_attr = sum(Attrition == "Yes") / n() * 100, meanAge = mean(Age)) %>% 
  ggplot(aes(x = StockOptionLevel, y = perc_attr, fill = StockOptionLevel)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  geom_text(aes(label = paste0(round(perc_attr, 1), "%")), vjust = 1.5, color = "white", size = 5) + 
  labs(title = "Attrition by Stock Option Level", x = "Stock Option Level", y = "Percent") + ylim(0, 30) +
  theme(legend.position = "none", axis.text.x = element_text(size = 12))
```

```{r}
##Correlation Heatmap
#https://www.sthda.com/english/wiki/ggcorrplot-visualization-of-a-correlation-matrix-using-ggplot2#google_vignette
install.packages("ggcorrplot")
library(ggcorrplot)
corr = round(cor(fl_num), 1)
head(corr)
ggcorrplot(corr, type = "lower", method = "circle")
```

```{r}
##Naive Bayes
seeds = 100
masterAcc = numeric(seeds)
masterSen = numeric(seeds)
masterSpec = numeric(seeds)
for (i in 1:seeds) 
  {
  set.seed(i)
  trainIndices = sample(seq(1:length(fl_fac$ID)), round(.7 * length(fl_fac$ID)))
  traindata = fl_fac[trainIndices, ]
  testdata = fl_fac[-trainIndices, ]
  model = naiveBayes(traindata[, c(7,13,14,17,18,21,25)], traindata$Attrition, laplace = 1)
  probs = predict(model, testdata[, c(7,13,14,17,18,21,25)], type = "raw")
  threshold = 0.2
  pred_labels = ifelse(probs[, "Yes"] > threshold, "Yes", "No")
  CM = confusionMatrix(table(pred_labels, testdata$Attrition))
  masterAcc[i] = CM$overall['Accuracy']
  masterSen[i] = CM$byClass['Sensitivity']
  masterSpec[i] = CM$byClass['Specificity']
}
MeanAcc = mean(masterAcc)
MeanSen = mean(masterSen)
MeanSpec = mean(masterSpec)
MeanAcc
MeanSen
MeanSpec
hist(masterAcc, xlab = "Accuracy", ylab = "Frequency", main = "Naive Bayes Accuracy")
hist(masterSpec, xlab = "Specificity", ylab = "Frequency", main = "Naive Bayes Specificity")
```

```{r}
##KNN

library(pROC)

#find best k
set.seed(10)
splitPerc = .7
trainIndices = sample(1:dim(fl_knn)[1],round(splitPerc * dim(fl_knn)[1]))
train = fl_knn[trainIndices,]
test = fl_knn[-trainIndices,]
accs = data.frame(accuracy = numeric(100), sensitivity = numeric(100), specificity = numeric(100), k = numeric(100))
for(i in 1:100)
{
  classifications = knn(train[,c(7,13,14,17,18,21,25)],test[,c(7,13,14,17,18,21,25)],train$Attrition, prob = TRUE, k = i)
  table(test$Attrition,classifications)
  CM = confusionMatrix(table(test$Attrition,classifications))
  accs$accuracy[i] = CM$overall[1]
  accs$sensitivity[i] = CM$byClass["Sensitivity"]
  accs$specificity[i] = CM$byClass["Specificity"]
  accs$k[i] = i
}
plot(accs$k,accs$accuracy, type = "l", xlab = "k")
which.max(accs$accuracy)
which.max(accs$specificity)
max(accs$accuracy)

#100 iteration knn
seeds = 100
masterAcc = numeric(seeds)
masterSen = numeric(seeds)
masterSpec = numeric(seeds)
for (i in 1:seeds) 
{
  set.seed(i)
  trainIndices = sample(1:dim(fl_knn)[1],round(.7 * dim(fl_knn)[1]))
  train = fl_knn[trainIndices,]
  test = fl_knn[-trainIndices,]
  classifications = knn(train[,c(7,13,14,17,18,21,25)],test[,c(7,13,14,17,18,21,25)],train$Attrition, prob = TRUE, k = 5)
  probs = ifelse(classifications == "Yes", attributes(classifications)$prob, 1 - attributes(classifications)$prob)
  threshold = .19
  NewClass = ifelse(probs > threshold, "Yes", "No")
  CM = confusionMatrix(table(NewClass, test$Attrition), mode = "everything")
  masterAcc[i] = CM$overall['Accuracy']
  masterSen[i] = CM$byClass['Sensitivity']
  masterSpec[i] = CM$byClass['Specificity']
}
MeanAcc = mean(masterAcc)
MeanSen = mean(masterSen)
MeanSpec = mean(masterSpec)
MeanAcc
MeanSen
MeanSpec
hist(masterAcc, xlab = "Accuracy", ylab = "Frequency", main = "KNN Accuracy")
hist(masterSpec, xlab = "Specificity", ylab = "Frequency", main = "KNN Specificity")
```

```{r}

```

